version: "3.8"
services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment: [ALLOW_ANONYMOUS_LOGIN=yes]
    ports: ["2181:2181"]

  kafka:
    image: bitnami/kafka:3.3.1
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports: ["9092:9092"]
    depends_on: [zookeeper]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  mock-external:
    image: python:3.10-slim
    volumes:
      - ./mock_external.py:/app/mock_external.py
    command: ["python", "/app/mock_external.py"]
    ports: ["8081:8081", "8082:8082"]
