spring:
  application:
    name: accounts-backend
  config:
    import: "optional:/config/"
  profiles:
    active: local
    include:
      - local

  datasource:
    url: jdbc:h2:mem:accounts;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn

server:
  port: 8080
